### ISSUE TITLE
Support for cloning plain git urls

### ISSUE THREAD

**Issue by mlhamel** [devbuddy/devbuddy#128]
We needs to support the use case of having someone cloning a git repos by url.

Ideally we would only support url scheme: `<HostingPlatform>/<OrganisationName>/<RepositoryName>.git`

**Comment by pior** [comment]
I think we should support the urls as provided by the hosting platforms.

Github:
- git@github.com:devbuddy/devbuddy.git
- https://github.com/devbuddy/devbuddy.git

Bitbucket:
- git@bitbucket.org:mlhamel/mlhamel.org.git
- https://bitbucket.org/mlhamel/mlhamel.org.git

Maybe just support SSH ?

**Comment by pior** [comment]
We'll see later if the HTTP protocol is needed.
