### ISSUE TITLE
Devbuddy doesn't have a logo

### ISSUE THREAD

**Issue by mlhamel** [devbuddy/devbuddy#208]
## Description

Debuddy doesn't have any icon actually and that's sad

## Proposition

Let's pick something like a panda? 

Maybe something like https://emojipedia.org/panda-face/

**Comment by merwok** [comment]
Panda with a hard hat or something related to programming, for the «dev» part.

**Comment by pior** [comment]
https://emojipedia.org/panda-face/

**Comment by pior** [comment]
Here is another option: the [dog-face](https://emojipedia.org/dog-face/) emoji from Google/Apache (a Shiba):

![devbuddy-shiba-logo-square](https://user-images.githubusercontent.com/60219/49674085-b2d4b180-fa3e-11e8-9026-55229fb3d303.png)

**Comment by pior** [comment]
Is a hard-hat a good symbol for the "dev" aspect ?

**Comment by pior** [comment]
Shiba it is
