### ISSUE TITLE
Implement a remote global metadata source   

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#230]
The `devbuddy` command could fetch some metadata from a global remote source.

Metadata like:
- latest revision for each Python/Go version (`3.6` -> `3.6.7`) (https://github.com/devbuddy/devbuddy/issues/199)
- latest revision of DevBuddy to show a message "A new version is available!"
- revision of DevBuddy that should be installed by the `install.sh` script
  - this would avoid having to update the `install.sh` on each release

Implementations for the source:
- A public GCS or S3 bucket (deployed by CI)

**Comment by pior** [comment]
No need for now

**Comment by jules2689** [comment]
If this is just metadata, then why not host it using Github pages. That's over a CDN, throw some generic static files up there, and avoids needing a piece that costs $
