### ISSUE TITLE
Add support for Go modules

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#282]
Go 1.11 introduced the [Go modules](https://github.com/golang/go/wiki/Modules).

There is two ways to activate the support:
- Invoke the go command in a directory outside of the $GOPATH/src tree, with a valid go.mod file in the current directory or any parent of it and the environment variable GO111MODULE unset (or explicitly set to auto).
- Invoke the go command with GO111MODULE=on environment variable set.

We should support having projects with and without modules, but it would be annoying to support two different directory tree (located in and out of GOPATH).
The remaining solution is to actively maintain the `GO111MODULE` env var.

The `go` task could be augmented with a `module` flag, to force the support of Go module:
```yaml
up:
  - go:
      version: 1.11
      module: true
```

Open questions:
- auto-detection with the presence of `go.mod`, or a `module` setting?
- what should we do when the user exits a project with `module=true`? 
  - reset to `GO111MODULE=auto` ? 
  - reset to the state of `GO111MODULE` before the project activation?

Ping @mlhamel

**Comment by pior** [comment]
@jduff Are you using Go? If so, do you have an opinion to the open questions?

**Comment by jduff** [comment]
I'm not using Go that much these days, but happy to chime in anyways :).

> * auto-detection with the presence of `go.mod`, or a `module` setting?

auto-detection with the ability to force or override with  a `module` setting sounds the most flexible to me. Easy to use out of the box, but if it gets it wrong or you have a weird case you can change it.

> * what should we do when the user exits a project with `module=true`?

I would reset to whatever `GO111MODULE` was before the project was activated, if possible. There are a few auto version switchers (chruby has one you can enable), whatever they do would be a good precedent to follow for this.
