### ISSUE TITLE
Restore envvars when leaving a project

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#302]
Currently autoenv features are **deactivated** by approximately reverting the mutations applied on the environment variables.

A better solution would be to record the previous state (unset or value) of each mutated variable.

Most features would actually not need more than just this automatic env restore.

#### Example with the Go feature: 
- sets a `GOROOT` variable
- possibly sets a `GO111MODULES` var
- prepends to `PATH`

Deactivation happens by:
- deleting `GOROOT`
- removing `GO111MODULES`
- search/remove the right element in `PATH`

#### Another example is the (upcoming) `.env` feature:
- set the variables defined in the `.env` file

Proper deactivation is currently impossible.

**Comment by pior** [comment]
Note: the currently "active" project is already tracked in the autoenv "state". 
We may need to re-spin its behavior for this.

**Comment by jules2689** [comment]
I'd recommend taking a peak at GitHub.com/Shopify/shadowenv which has this capability.
