### ISSUE TITLE
Looking for help?

### ISSUE THREAD

**Issue by jules2689** [devbuddy/devbuddy#304]
I'd love to help out if anything is needed here. Got lots of lessons I can share.

Cheers,

**Comment by pior** [comment]
Absolutely!

I guess we can use the issues or [Gitter](https://gitter.im/devbuddy/Lobby) for the coordination.

There is a lot of work already captured as issues, [big](#90) or [small](#82).
We also have a [board](https://github.com/devbuddy/devbuddy/projects/1) with a rough prioritization. 

But just create an issue if you find something missing.

Just self-assign an issue (or leave a comment) if you want to start working on something

**Comment by jules2689** [comment]
Awesome! I'll take a look in the coming week
