### ISSUE TITLE
installer: support overriding vars with envvars

### ISSUE THREAD

**Issue by merwok** [devbuddy/devbuddy#349]
It would be nice to be able to run the install script with custom envvars defining DEST or SUDO, to customize things without needed sed / local edit.

**Comment by pior** [comment]
`DEST`:  you want to be able to specify the installation path (something else than `/usr/local/bin`)

`SUDO`: what is your use-case? Is it because you want to install in your home? Like `~/.bin` ?

**Comment by merwok** [comment]
`DEST`: yes exactly, would like to change the default here https://github.com/devbuddy/devbuddy/blob/master/install.sh#L5 to somewhere else (in this case `~/.usr/bin` which is in my `PATH`)

`SUDO`: not all distros use sudo, and not all `DEST`s require elevated rights, so this would be a nice complement to the previous var.

**Comment by pior** [comment]
Thank you for reporting this @merwok 💯

**Comment by pior** [comment]
Released in v0.11.1
