### ISSUE TITLE
Adds support for zsh

### ISSUE THREAD

**Issue by mlhamel** [devbuddy/devbuddy#68]
It's currently broken cause of the missing support of `prompt-command` in zsh

We could probably follow something like:

https://superuser.com/questions/735660/whats-the-zsh-equivalent-of-bashs-prompt-command

**Comment by pior** [comment]
It seems like the integration tests are running fine. 
Which is not unlikely given that the direct interaction with the shell is quite limited to reading/mutating environment variable.

The integration tests are testing the `dad --shell-hook` behavior. 
But **not** the prompt hook per se.

Looks like a good news as supporting Zsh **may** be limited to implementing an alternative `prompt-command`.

Doc: http://zsh.sourceforge.net/Doc/Release/Functions.html#Hook-Functions

**Comment by pior** [comment]
The definition of a "zsh support" was a bit vague. Did we get a reasonable zsh support with #107 ?
Ping @mlhamel @paccorsi

**Comment by mlhamel** [comment]
My understanding is yes but what would be missing right now would be to add the zsh completion but i think it worth a separated ticket

**Comment by pior** [comment]
Zsh completion was shipped a long time ago 🎉
