### ISSUE TITLE
Find a better project name

### ISSUE THREAD

**Issue by pior** [devbuddy/devbuddy#71]
The project name: `dad` is a pretty bad. (Chosen because it's quick to type).

A good name would be:
- quick to type
- easy to Google

Bonus points for:
- available domain on cool TLDs like `.sh` or `.io`
- a name associated with a nice emoji

A portmanteau name is a pretty nice option to be Googleable AND a short command name.

**Comment by mlhamel** [comment]
Continuing on the `portemanteau` trend `patere` would be shorter what do you think?

**Comment by mlhamel** [comment]
and then our shorter command could be `pat`

**Comment by pior** [comment]
By "portmanteau", I meant a name like `homebrew`, which is googleable, and provide a nice short cli name: `brew`.

**Comment by pior** [comment]
From famous computer scientists: 
- `ada`, Ada Lovelace
- `hop`, Grace Hopper

**Comment by mlhamel** [comment]
What about `devhop` and the command would be `hop`?

**Comment by manumilou** [comment]
`godev` ?

**Comment by pior** [comment]
So we may have a good candidate:
Project name: _Hopper_
Command: `hop`

**Comment by mlhamel** [comment]
What about `buildingbox`

and the command could be `box`

**Comment by mlhamel** [comment]
`refine`
and we could get `refcmd` is available on github

**Comment by mlhamel** [comment]
`refine`: improve (something) by making small changes, in particular make (an idea, theory, or method) more subtle and accurate.

For the other one:
`buildingbox`: https://www.lego.com/en-us/service/buildinginstructions/search?initialsearch=10695#?text=10695

**Comment by merwok** [comment]
IMHO the project name, repo name and command name should be as similar as possible (e.g. difference of caps or hyphens only).  A made-up name or portmanteau helps referencing!

The name should be a shortcut for the project description.

Help onboard developers: `board`, `onboard`, `ondev`

I quite like `godev` but Go-language overloads tool names starting with `go`.

Sit down and get coding: `sitdown`

Five minutes to get app running: `five` (super not referenceable)

Tool to set up your development environment: `setup-tool`? :trolleybus:

**Comment by pior** [comment]
`tachyon`? `tac`

**Comment by merwok** [comment]
rubberduck, comme le canard en plastique qui aide à résoudre des problèmes.

**Comment by pior** [comment]
The special committee wants `DevBuddy` (`bud`). Let's try to please it.

**Comment by mlhamel** [comment]
Related to `devbuddy`, we've got a few propositions like:
a) `Devbuddy` project name, `dev` for the command
b) `Devbuddy` project name `buddy` for the command 
     - Maybe with an shell alias to `bud`
c) `Devbuddy` project name, `bdy` for the command

**Comment by mlhamel** [comment]
Also, are we keeping the 🐼?
